FROM postgres:9.6
# Set environment variables
ENV POSTGRES_USER {}'.format(os.getenv('POSTGRES_USER'))'
ENV POSTGRES_PASSWORD {}'.format(os.getenv('POSTGRES_PASSWORD'))'
ENV POSTGRES_DB {}'.format(os.getenv('POSTGRES_DB'))'