version: '2'
 
services:
  web:
    container_name: vachan-api
    restart: always
    build: .
    expose:
      - "8000"
    volumes:
      - /usr/src/vachan-api
    command: /usr/local/bin/gunicorn -w 2 -b :8000 agmt/main:app

  nginx:
    restart: always
    build: conf/nginx
    ports:
      - "80:80"
    volumes:
      - /www/vachan-api
    volumes_from:
      - web
    depends_on:
      - web
 