version: '2'
 
services:
  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgresql
    env_file:
      - .env.dev
    volumes_from:
      - data
    ports:
      - "5432:5432"

  api:
    container_name: vachan-api
    restart: always
    build: .
    expose:
      - "8000"
    volumes:
      - /usr/src/vachan-api
    command: /usr/local/bin/gunicorn -w 2 -b :8000 agmt/main:app
    depends_on:
      - postgres

  nginx:
    restart: always
    build: conf/nginx
    ports:
      - "80:80"
    volumes:
      - /www/vachan-api
    volumes_from:
      - api
    depends_on:
      - api
 