name: Build & Deploy

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: appleboy/ssh-action@master
        name: Deploy Fast-API app
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          # PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}

        with:
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"


